version: '2'
services:
# mysql service for qucheng
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Qucheng
      - MYSQL_DATABASE=qucheng
  
  qucheng:
    image: hub.qucheng.com/platform/qucheng:${TAG}
    container_name: qucheng
    ports:
      - '4080:80'
    volumes:
      - 'qucheng_data:/data'
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass4Qucheng
      - MYSQL_DB=qucheng
      - CNE_API_TOKEN=gwaN4KynqNqQoPD7eN8s
      - CNE_API_HOST=http://cne.internal-pre.chandao.net
      - CLOUD_API_HOST=http://cne-market.internal-pre.chandao.net
      - CLOUD_DEFAULT_CHANNEL=test

  qucheng-dev:
    image: hub.qucheng.com/platform/qucheng:${TAG}
    container_name: qucheng-dev
    ports:
      - '4081:80'
    volumes:
      - 'qucheng-dev_data:/data'
      - .:/apps/qucheng
      - ./docker/alpine/rootfs/apps/qucheng/config/my.php:/apps/qucheng/config/my.php
    depends_on:
      - mysql
    environment:
      - RUN_MODE="dev"
      - DEBUG=true
      - PAUSE=0
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass4Qucheng
      - MYSQL_DB=qucheng_dev
      - CNE_API_TOKEN=gwaN4KynqNqQoPD7eN8s
      - CNE_API_HOST=http://cne.internal-pre.chandao.net
      - CLOUD_API_HOST=http://cne-market.internal-pre.chandao.net
      - CLOUD_DEFAULT_CHANNEL=test

volumes:
  db:
    driver: local
  qucheng_data:
    driver: local
  qucheng-dev_data:
    driver: local
