version: '2'
services:
# mysql service for zentao
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Qucheng
      - MYSQL_DATABASE=qucheng
  qucheng:
    build:
        context: .
        dockerfile: docker/Dockerfile
    image: hub.qucheng.com/platform/qucheng:${TAG}
    container_name: qucheng
    ports:
      - '4080:80'
    volumes:
      - 'qucheng_data:/data'
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass4Qucheng
      - MYSQL_DB=qucheng
      - CNE_API_TOKEN=gwaN4KynqNqQoPD7eN8s
      - CNE_API_HOST=http://cne.internal-pre.chandao.net
      - CLOUD_API_HOST=http://cne-market.internal-pre.chandao.net
      - CLOUD_DEFAULT_CHANNEL=test
      - APP_DOMAIN=test

volumes:
  db:
    driver: local
  qucheng_data:
    driver: local
